### ISSUE TITLE
为什么聊天视频流会推不上？

### ISSUE THREAD

**Issue by 1604653069** [shenbengit/srs-rtc-server#2]
[![xdPYEd.jpg](https://s1.ax1x.com/2022/10/13/xdPYEd.jpg)](https://imgse.com/i/xdPYEd)

**Comment by 1604653069** [comment]
那个推流的地址，我在Constant.kt文件中已经改了，为什么还是192.168.2.235，请问这个地址要在哪里可以改？

**Comment by shenbengit** [comment]
1、clear\rebuild 项目；
2、全局搜索。

请在对应的项目下提issue。
